# Grafana instance configuration
grafana:
  # API key for grafana with admin level, needed to request datasources
  # REQUIRED
  admin_api_key: SOME_API_KEY_IN_BASE_64
  # Base URL of your grafana instance including scheme and port
  # REQUIRED
  base_url: https://grafana.example.com:3000
  # Default time range in seconds, subtracted from the time the program gets executed
  # or from the flag --to if specified.
  # This will be overridden with --from.
  # OPTIONAL (default: 3600)
  default_time_range: 3600
  # If the certificate of the instance should be verified
  # OPTIONAL (default: true)
  tls_verify: true

# Which dashboards shall be plotted
dashboards:
  # Dashboard uid REQUIRED
  # This dashboard does not have variables specified, so they will be ignored and
  # only the default values are used
  - uid: oOf-u1V7z
    # Render panels which are part of a collapsed row (default: false)
    collapsed: true
  # Another dashboard with specified variables and an 'ignore' regex pattern
  # Only the specified variables are used when plotting panels, others are ignored or
  # only their default is used automatically by grafana
  # When resolving variable values the ones matching 'ignore' will be filtered out.
  - uid: BJO0XQS7k
    variables: ['job', 'protocol']
    ignore: '127.0.0.1:*|172.0.0.10:*'

prometheus:
  # Currently this program is very limited and the prometheus node exporter job name
  # (from prometheus's scrape_config) must be given
  # This will be placed in any query which contains $job
  node_exporter_job_name: node

plots:
  # Absolute or relative path to the directory to store the plots into
  # OPTIONAL (default: ./plots)
  output_dir: plots

log_level: info